-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ("세단", "SUV")
    AND D.DURATION_TYPE = "30일 이상"
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "2022-11-30" AND
            END_DATE >= "2022-11-01"
    )
HAVING FEE BETWEEN 500000 AND 2000001
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC