-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_INTAKE LIKE 'Intact Male' AND B.SEX_UPON_OUTCOME LIKE 'Neutered Male')
    OR (A.SEX_UPON_INTAKE LIKE 'Intact Female' AND B.SEX_UPON_OUTCOME LIKE 'Spayed Female')