-- 코드를 입력하세요
SELECT TITLE, a.BOARD_ID, REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
From USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
where  a.BOARD_ID = b.BOARD_ID
and a.CREATED_DATE LIKE "2022-10%"
order by b.CREATED_DATE,TITLE